<a href="https://colab.research.google.com/github/yumichaela/Study_BasicPytorch/blob/main/Numpy%EC%97%B0%EC%8A%B5_0118.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#2.3 Numpy

In [2]:
#여러가지 배열
import numpy as np
a = np.array([1, 5, 0, -1])
b = np.ones((2, 2, 2))
c = np.zeros((2, 3))
d = np.arange(10)
e = np.linspace(0, 10, 5)
f = np.random.randint(2, 10, 5)

print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)
print("f:", f)



a: [ 1  5  0 -1]
b: [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
c: [[0. 0. 0.]
 [0. 0. 0.]]
d: [0 1 2 3 4 5 6 7 8 9]
e: [ 0.   2.5  5.   7.5 10. ]
f: [7 5 2 7 4]


In [4]:
c.astype('int')

array([[0, 0, 0],
       [0, 0, 0]])

In [2]:
#조건문을 이용한 인덱스 검색
import numpy as np
mu = 0
sigma = 1
arr = np.random.normal(mu, sigma, (5,3))
arr

array([[-1.78674195, -0.21811968, -0.36913732],
       [-1.28060287, -1.68028562, -0.48631135],
       [-1.43119356,  0.10264446, -1.44551483],
       [-1.22738117,  1.23378639,  0.24937032],
       [-0.33148999, -0.91723811, -1.66906078]])

In [3]:
np.where(abs(arr) > sigma, "out", "in")

array([['out', 'in', 'in'],
       ['out', 'out', 'in'],
       ['out', 'in', 'out'],
       ['out', 'out', 'in'],
       ['in', 'in', 'out']], dtype='<U3')

In [6]:
#배열의 기본 연산
a = np.array([[1,3],[0,-1]])
b = np.random.randint(0, 10, 4).reshape(2,2)
a + b

array([[ 7, 12],
       [ 4,  8]])

In [31]:
#2.4.5 try & except 문(p.52)

x = [1,2,3,"s",4,5]
for i in x:
  try:              #try 내에서 오류가 생기면 except문으로 넘겨주고, 오류가 없으면 그대로 실행함
    y = i + 1
    print(y)
  except:
    pass   #오류가 넘어와도 그냥 진행하겠다!

#데이터가 많으면 오류를 전부 수정하는데 오래 걸림 > 소수의 오류로 인해 알고리즘이 멈추는 것을 방지해줌

2
3
4
5
6


In [ ]:
#2.5 함수와 모듈

In [10]:
#함수
import numpy as np

def sincos(x):
  return np.sin(x) + np.cos(x)

sincos([1,2])

array([1.38177329, 0.49315059])

In [ ]:
#2.6 클래스

In [16]:
import numpy as np

class DataPreprocessing:
  def __int__(self, data, target): #클래스 내부에 외부 변수를 불러올 때 __int__ 함수 사용, 괄호 안에 self 넣어주고, 추가적으로 원하는 변수 나열
    self.data = data
    slef.target = target
    self.num_instances = self.data.shape[0] # 0 or O ?
    self.num_features = self.date.shape[1] 
  def minimax(self): #클래스 내부의 함수에는 self를 반드시 기입한다
    for i in range(self.num_features): #변수에도 self를 붙여 선언할 수 있으며 > 클래스 내부의 함수들에서 별도 선언 없이 사용 가능 
      col = self.data[:,i]
      self.data[:,i] = (self.data[:,i]-np.min(col))/(np.mac(col)-np.min(col)) #??? 기존 값이 스케일링 된 값으로 대체되어 self가 열 기준으로 계산된 0 이상 1이하의 값을 가진 데이터로 변환됨
    return self
  def normarlization(self):
    for i in range(self.num_features):
      col = self.data[:,i]
      mu,sigma = np.mean(col), np.std(col)
      self.data[:,i] = (self.data[:,i]-mu)/sigma
    return self

In [17]:
def scaler(self, scaling=None):
  if scaling == 'minimax':
    self.minimax()
  elif scaling == 'standard':
    self.normalizaion()
  else:
    pass
  return self.data

In [ ]:
#클래스 불러오기
data = np.random.normal(0,10, (5,5))
target = np.random.normal(0,1, 5)
print(data)
data_processor = DataPreprocessing(data,target) #클래스명, 필요한 변수 넣어주고, 변수명 선언한다
data = data_processor.scaler('minimax') #클래스의 함수or변수를 사용하고 싶을 때? data_processor.함수명 // Scaler 함수는 scaling이라는 변수를 받고, 기본 값으로 None이 들어가 있음,
print(data)


In [ ]:
#클래스의 상속
class DataPipeline(DataPreprocessing): 
  def__int__(self, data):
    self.data = data
    self.num_features = self.data.shape[1]
pipe = DataPipeline(data) #(스케일링에 필요한) 변수를 가지고 있는 클래스를 선언
data = pipe.scaler('minimax') #DataPreprocessing 내에 있는 scaler 함수명 그대로 사용

In [ ]:
#2.7 그래프 그리기

In [23]:
import numpy as np
from matplotlib import pyplot as plt

epoch = np.arange(1,100) #arange함수:실수 단위도 표현 가능한 range 함수
train_loss = 1.5/(epoch) #예시
val_loss = .3+1/(epoch) #예시

In [27]:
plt.figure(figsize = (10,5) #그래프의 틀을 담당
plt.plot(train_loss),'r-*') #(리스트or넘파이 배열을)2차원 그래프로 표현해줌, (예시처럼)x변수 없으면, 자동으로 0부터 정수 들어감, r-:빨간선, *:별로 표시
plt.plot(val_loss, 'b-*')
plt.legend(['train','validation'] #범례를 나타내는 함수, 함수가 그려지는 순서대로 할당됨
plt.title("MNIST")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.show()

#다중 그래프 그리기(p.60 참고)


SyntaxError: ignored

In [ ]:
#2.8 폴더 및 파일 관리

In [33]:
#폴더 생성
import os

def newfolder(directory):
  try:
    if not os.path.exists(directory):
      os.makedirs(directory)
  except OSError:
      print('Error')

parent_folder = './new' #./:현재 디렉토리, so 현재 디렉터리에서 new라는 폴더를 생성한다는 뜻
newfolder(parent_folder)

In [ ]:
#경로 불러오기
import glob  #glob()함수:필요한 경로를 리스트에 담을 수 있음, 
path = glob.glob('./data/*') #(현재 디렉터리에서) data폴더 안에 모든 폴더 and 파일에 관한 경로를 불러옴 // Q:data 폴더에 png확장자만 불러오려면? A:glob.glob('./data/*.png)
print(path)

In [ ]:
#파일 불러오기 및 저장하기(p.63)

In [ ]:
#2.9 터미널에서 파이썬 실행하기

In [ ]:
#3.3 데이터 세트 분할

In [36]:
import numpy as np
from sklearn.model_selection import train_test_split #(skleran라이브러리의 train~split:원하는 분할 비율로 학습 & 평가 데이터로 나눌 수 있음)

X,y = np.arange(1000).reshape((100,10)),np.arange(100)
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0) #test_size=0.3 > 평가 데이터가 30%, 학습 데이터가 70% 